### ISSUE TITLE
No module named hexdump

### ISSUE THREAD

**Issue by ankit0183** [SafeBreach-Labs/SirepRAT#6]
after install of hex dump still showing the same error
"Traceback (most recent call last):
  File "SirepRAT.py", line 47, in <module>
    import hexdump
ImportError: No module named hexdump
"

**Comment by J020203** [comment]
Install hexdump

pip install hexdump

Then its just got a lot of errors :3

**Comment by dorazouri** [comment]
> after install of hex dump still showing the same error
> "Traceback (most recent call last):
> File "SirepRAT.py", line 47, in
> import hexdump
> ImportError: No module named hexdump
> "

This is an external module, and as @J020203 had mentioned - `pip install` should do.
If it doesn't, I'd make sure you are running `SirepRAT.py` with the same python version of your `pip` as it is common to have multiple python installations. Other possible reasons might involve your PATH system variable, which you could inspect using `print sys.path`

**Comment by J020203** [comment]
> > after install of hex dump still showing the same error
> > "Traceback (most recent call last):
> > File "SirepRAT.py", line 47, in
> > import hexdump
> > ImportError: No module named hexdump
> > "
> 
> This is an external module, and as @J020203 had mentioned - `pip install` should do.
> If it doesn't, I'd make sure you are running `SirepRAT.py` with the same python version of your `pip` as it is common to have multiple python installations. Other possible reasons might involve your PATH system variable, which you could inspect using `print sys.path`

So how could i run SirepRAT with the same version of pip with python?
Would work with python3?, How?

**Comment by dorazouri** [comment]
SirepRAT was built for `python2` and will not work with `python3`.

`pip.exe` is a utility for package management for python. It is located under the `PYTHON_INSTALLATION_DIR\Scripts` directory.
The thing is, if you have multiple python installations on the same machine, there's a potential confusion, i.e. you install a package with the `pip` executable of python3, but then run your script using python2 (where the desired package is not installed).

I'm suggesting this might be the case here, and would recommend you trying to run `pip` with an explicit path, e.g. `C:\**Python27**\Scripts\pip.exe install hexdump`. Then, you should run the script using the same python version, e.g.: `C:\**Python27**\python.exe SirepRAT.py`.

This is just a guess but hope it helps.
Otherwise - there are countless troubleshooting articles for this general ImportError message, some involve modifying the `PATH` system variable.

Closing issue as this is out of the scope of this repository.

**Comment by Dxter95** [comment]
after running the SireRat.py they give this error 
from common.mappings import SIREP_COMMANDS, RESULT_TYPE_TO_RESULT
  File "/home/kali/HTB/Omni/SirepRAT/common/mappings.py", line 65, in <module>
    ResultRecordType.SystemInformation.value: results.SystemInformationResult,
AttributeError: 'int' object has no attribute 'value'

**Comment by dorazouri** [comment]
> after running the SireRat.py they give this error
> from common.mappings import SIREP_COMMANDS, RESULT_TYPE_TO_RESULT
> File "/home/kali/HTB/Omni/SirepRAT/common/mappings.py", line 65, in
> ResultRecordType.SystemInformation.value: results.SystemInformationResult,
> AttributeError: 'int' object has no attribute 'value'

Please see solution on previous issue:
https://github.com/SafeBreach-Labs/SirepRAT/issues/2

**Comment by Dxter95** [comment]
i see it and fix it thank you

**Comment by dorazouri** [comment]
@Dxter95 SirepRAT v2 is now committed and supports python3, for better experience with Kali! See latest code and [release](https://github.com/SafeBreach-Labs/SirepRAT/releases/tag/v2.0.0).
